#' Calculate the SI for a list (by route_type) of tidygtfs objects
#'
#' @param list_gtfs the list (by route_type) of tidygtfs objects
#' @param stops_in_or_near_areas the list (by route_type) of stop_in_or_near_areas, 
#' created by the stop_in_walk_dist function
#' @param date_ymd the date for which the SI should be calculated
#' @param start_hms the start time for which the SI should be calculated, 
#' inclusive of services that arrive at that time precisely
#' @param end_hms the end time for which the SI should be calculated, 
#' exclusive of services that arrive at that time precisely
#' @param verbose if TRUE function will print intermediate tables and steps.
#'
#' @return a list (by route_type) of dataframes with area_id and matching SI scores
#' @export
#'
#' @examples
#'#load the revised mornington GTFS data
#'library(dplyr)
#'list_gtfs = gtfssupplyindex:::gtfs_by_route_type(system.file(
#'  "extdata/mornington180109",
#'  "gtfs.zip", 
#'  package = "gtfssupplyindex", 
#'  mustWork = TRUE))
#'
#'areas_of_interest <- load_areas_of_interest(absmapsdata::sa22021 %>% 
#'             filter(sa3_name_2021 ==  "Mornington Peninsula") %>% 
#'                                              select(sa2_code_2021),  
#'                                            area_id_field = "sa2_code_2021")
#'
#'buffer_distance <- gtfssupplyindex:::load_buffer_zones()
#'
#'stops_in_or_near_areas <- gtfssupplyindex:::stops_in_walk_dist(
#'  list_gtfs = list_gtfs, 
#'  areas_of_interest = areas_of_interest,
#'  EPSG_for_transform = 28355,
#'  verbose = FALSE
#')
#'
#'####----run SI.calc function to build si_by_mode_and_time list (by route_type) of tables
#'
#'si_by_route_type <- si_calc(
#'  list_gtfs = list_gtfs,
#'  stops_in_or_near_areas = stops_in_or_near_areas, 
#'  date_ymd = lubridate::ymd("2018-12-30"), 
#'  start_hms = lubridate::hms("10:30:00"),
#'  end_hms = lubridate::hms("16:00:00"),
#'  verbose = TRUE)

 
si_calc <- function(
    list_gtfs, 
    stops_in_or_near_areas, 
    date_ymd, 
    start_hms,
    end_hms,
    verbose = FALSE){
  
  
  
  # add route_type names to list (by route) of tidy_gtfs
  stops_in_or_near_areas_list_with_route_name <- mapply(function(x, nm){ 
    route_type_name = nm
    x <- list(x)
    append(x, 
           route_type_name)
                }, 
    stops_in_or_near_areas, names(stops_in_or_near_areas), SIMPLIFY=FALSE)
  
  
  # apply SI_calc_one_route function to list (by route) of stops_in_or_near_areas
  si_by_mode_and_time <- lapply(stops_in_or_near_areas_list_with_route_name, si_calc_one_route,
                                  list_gtfs,
                                  date_ymd,
                                  start_hms,
                                  end_hms,
                                  verbose)
 
  return(si_by_mode_and_time)
}

#' Calculate the SI values for an individual mode (route_type)
#' 
#' Called by the SI_calc function to generate each datatable of area_id and SI
#' 
#' @param stops_in_or_near_areas_dataframe a datatable of 
#' stop_id, area_id and area_terms, as generated by the stops_in_walk_dist function 
#' and stored as list elements in stops_in_or_near_areas
#' @param list_gtfs the list (by route_type) of tidygtfs objects
#' @param date_ymd the date for which the SI should be calculated
#' @param start_hms the start time for which the SI should be calculated, 
#' inclusive of services that arrive at that time precisely
#' @param end_hms the end time for which the SI should be calculated, 
#' exclusive of services that arrive at that time precisely
#' @param verbose if TRUE function will print intermediate tables and steps.
#'
#' @return a datatable with area_id and matching SI scores
#' @export
#'
#' @examples
#' #'#load the revised mornington GTFS data
#' library(dplyr)
#'list_gtfs = gtfssupplyindex:::gtfs_by_route_type(system.file(
#'  "extdata/mornington180109",
#'  "gtfs.zip", 
#'  package = "gtfssupplyindex", 
#'  mustWork = TRUE))
#'
#'areas_of_interest <- load_areas_of_interest(absmapsdata::sa22021 %>% 
#'                                              filter(sa3_name_2021 == "Mornington Peninsula") %>% 
#'                                              select(sa2_code_2021),  
#'                                            area_id_field = "sa2_code_2021")
#'
#'buffer_distance <- gtfssupplyindex:::load_buffer_zones()
#'
#'stops_in_or_near_areas <- gtfssupplyindex:::stops_in_walk_dist(
#'  list_gtfs = list_gtfs, 
#'  areas_of_interest = areas_of_interest,
#'  EPSG_for_transform = 28355,
#'  verbose = FALSE
#')
#
#'
#'si_by_mode_and_time_one_route_type <- si_calc_one_route(
#'  stops_in_or_near_areas_dataframe = 
#'  stops_in_or_near_areas_list_with_route_name <- mapply(function(x, nm){ 
#'    route_type_name = nm
#'    x <- list(x)
#'    append(x, 
#'           route_type_name)
#'                }, 
#'    stops_in_or_near_areas, names(stops_in_or_near_areas), SIMPLIFY=FALSE)[[1]],
#'  list_gtfs = list_gtfs,
#'  date_ymd = lubridate::ymd("2018-12-30"), 
#'  start_hms = lubridate::hms("10:30:00"),
#'  end_hms = lubridate::hms("16:00:00"),
#'  verbose = TRUE)

si_calc_one_route <- function(
    stops_in_or_near_areas_dataframe, 
    list_gtfs,
    date_ymd, 
    start_hms,
    end_hms,
    verbose = FALSE){

  #obtain the arrivals by stop_id using arrivals function
  arrivals_by_stop_id <- gtfssupplyindex::arrivals(
    gtfs = list_gtfs[[stops_in_or_near_areas_dataframe[[2]]
    ]],
    stop_ids = unique(stops_in_or_near_areas_dataframe[[1]]["stop_id"]),
    date_ymd = "2018-12-30",
    start_hms = start_hms,
    end_hms = end_hms
  )
  
  #join number of arrivals per stop to the stops_in_or_near_areas table
  stops_in_or_near_areas_dataframe[[1]] <- left_join(
    stops_in_or_near_areas_dataframe[[1]], 
    arrivals_by_stop_id, 
    by = "stop_id")

#Calculate SI as areas_terms multiplied by the arrivals (SLn)    
stops_in_or_near_areas_dataframe[[1]]$SI <- 
  stops_in_or_near_areas_dataframe[[1]]$area_terms *
    stops_in_or_near_areas_dataframe[[1]]$arrivals

#Sum SI for each area_id
si_by_route_type <- aggregate(
  stops_in_or_near_areas_dataframe[[1]]$SI,
  by = list(
    area_id = stops_in_or_near_areas_dataframe[[1]]$area_id),
  FUN = sum
  ) 
names(si_by_route_type) <- c("area_id", "SI")

return(si_by_route_type)
}